
export default {

    splashLogo: require("../../res/star.png"),
    splashBg: require("../../res/ic_splash_bg.png"),
    ic_fb: require("../../res/ic_fb.png"),
    ic_google: require("../../res/ic_google.png"),
    ic_twitter: require("../../res/ic_twitter.png"),
    ic_eye: require("../../res/ic_eye.png"),
    ic_eye_close: require("../../res/ic_eye_close.png"),
    ic_tick: require("../../res/ic_tick.png"),
    ic_back: require("../../res/ic_back.png"),
    ic_point_big: require("../../res/ic_point_big.png"),
    ic_point_small: require("../../res/ic_point_small.png"),
    ic_logout: require("../../res/Logout.png"),
    ic_weight: require("../../res/ic_weight.png"),
    ic_about: require("../../res/ic_about.png"),
    ic_menu: require("../../res/ic_menu.png"),
    ic_setting: require("../../res/Setting.png"),
    ic_hand: require("../../res/ic_hand.png"),
    ic_leg: require("../../res/ic_leg.png"),
    ic_body: require("../../res/ic_body.png"),
    ic_time: require("../../res/ic_time.png"),
    ic_add: require("../../res/ic_add.png"),
    ic_right: require("../../res/ic_right.png"),
    ic_left: require("../../res/ic_left.png"),
    ic_download: require("../../res/ic_download.png"),
    ic_down: require("../../res/ic_down.png"),
    ic_clock: require("../../res/ic_clock.png"),
    ic_lift: require("../../res/ic_lift.png"),
    ic_dot_menu: require("../../res/ic_dot_menu.png"),
    ic_calendar: require("../../res/Calendar.png"),
    ic_document: require("../../res/Document.png"),
    ic_add_purple: require("../../res/ic_add_purple.png"),
    ic_bold_arrow: require("../../res/ic_bold_arrow.png"),
    ic_pause: require("../../res/ic_pause.png"),
    ic_home: require("../../res/Home.png"),
    ic_folder: require("../../res/Folder.png"),
    ic_note: require("../../res/note.png"),
    ic_dumble: require("../../res/ic_dumble.png"),
    ic_minus: require("../../res/ic_minus.png"),
    ic_add_new: require("../../res/ic_add_new.png"),
    ic_divider: require("../../res/divider.png"),
    ic_chest: require("../../res/ic_chest.png"),
    ic_hips: require("../../res/ic_hips.png"),
    ic_left_arm: require("../../res/ic_left_arm.png"),
    ic_right_arm: require("../../res/ic_right_arm.png"),
    ic_left_thigh: require("../../res/ic_left_thigh.png"),
    ic_right_thigh: require("../../res/ic_right_thigh.png"),
    ic_waist: require("../../res/ic_waist.png"),
    camera: require("../../res/camera.png"),
    photo: require("../../res/photo.png"),
    contacts: require("../../res/contacts.png"),
    location: require("../../res/location.png"),
    
}